version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: barao_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=barao_db
      - POSTGRES_USER=barao_user
      - POSTGRES_PASSWORD=barao_password
    ports:
      - "5432:5432"

volumes:
  postgres_data: